### ISSUE TITLE
httpdocs/config/../app/autoload.php): failed to open stream:

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/autoupgrade#116]
Hello
I'm facing an issue after an upgrade to latest PS 1.7 version via autoupgrade mode

my wabsite shows this error
Warning: require(/var/www/vhosts//httpdocs/config/../app/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts//httpdocs/config/autoload.php on line 33

Warning: require(/var/www/vhosts//httpdocs/config/../app/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/playstore.ma/httpdocs/config/autoload.php on line 33

Fatal error: require(): Failed opening required '/var/www/vhosts//httpdocs/config/../app/autoload.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts//httpdocs/config/autoload.php on line 33
any idea please
regards

**Comment by matks** [comment]
Hello,

By "latest PS 1.7 version" do you mean PS 1.7.4.2 ?

**Comment by Quetzacoalt91** [comment]
Hmm, we had this issue when the provided release of PrestaShop wasn't correct (the module was moving all the files in a subfolder), but that was fixed in https://github.com/PrestaShop/autoupgrade/pull/110 by checking the release content.

I do not know if you have the same issue here, but on our side we had this error as a consequence. Have you used (at least) the v4.0beta-5 of the module?

**Comment by Quetzacoalt91** [comment]
As said, the related issue we already got was fixed by #110.

If this issue still occurs with the latest versions of the module, feel free to reopen this issue.

Regards
