### ISSUE TITLE
Core folder not cleaned after upgrade

### ISSUE THREAD

**Issue by 123monsite-regis** [PrestaShop/autoupgrade#193]
**Describe the bug**
After unziping, and scratching old version into new version,
Some old classes or controllers still remain and can causes troubles after

**Upgrade environment (please complete the following information):**
 - Version you started from: [e.g. 1.6.14]
 - Version you upgrade to: [e.g. 1.7.8.0 - Beta]
 - Way of upgrade: One click upgrade module
 - Step concerned: After upgrade finished correctly, when testing shop

**Displayed log**
```
PHP Fatal error:  Call to undefined method NewProductsController::productSort() in controllers/front/NewProductsController.php
```

**Expected behavior**
controllers/front/NewProductsController.php should not exist anymore after an upgrade ,as it is nosow located on controllers/front/listing/NewProductsController.php

**Additional context**
deletting it manually after update is OK
other controllers are concerned

**Comment by Quetzacoalt91** [comment]
I guess this is caused by a lack of information from a manual upgrade with a zip.

When we follow the default major / minor upgrades, a list of file with their md5 is provided, allowing the core to know what files must be deleted.

There is nothing you can currently do, the stable release (with its md5 file) should fix the issue.

**Comment by 123monsite-regis** [comment]
thanks a lot,
your guess is right.
I close this issue, as it is not a bug.
